# Make file for Battery Manager
Batman: Batman.cpp INA219 Tolako5V
	g++ -std=c++0x Batman.cpp INA219 Tolako5V -o Batman 

#TODO Tolako5V files are not in Batman root
INA219: INA219.cpp INA219.h

#TODO Tolako5V files are not in Batman root either
Tolako5V: Tolako5V.cpp Tolako5V.h

