sendMessage: sendmessage.cpp 	
	g++ -std=c++0x -o sendmsg sendmessage.cpp commsys -lwiringPi

readH2O: readH2O.cpp hcsr04 
	g++ -std=c++0x -o readH2O readH2O.cpp hcrsr04 -lwiringPi

hcsr04: /home/pi/Documents/GitHub/Personal/Projects/I61_Internship/HC-SR04_Ultrasonic/HC-SR04.cpp
	g++ -c /home/pi/Documents/GitHub/Personal/Projects/I61_Internship/HC-SR04_Ultrasonic/HC-SR04.cpp -lwiringPi

commsys: /home/pi/Documents/GitHub/Personal/Projects/I61_Internship/Communication_System/CommSys.cpp
 
